version: '2'
services:
  db:
    container_name: mariadb
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
  wordpress:
    container_name: wordpress-wpexpress
    image: wordpress:latest
    external_links:
      - mariadb:mysql
      - mailhog
    restart: always
    environment:
      VIRTUAL_HOST: wpexpress.test
      WORDPRESS_DB_NAME: wpexpress.test
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      TZ: America/Toronto
    volumes:
      - ./:/var/www/html/wp-content/mu-plugins
    ports:
      - 80
volumes:
  mysql:
